/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_ucu;

//import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;
import utils.ManejadorDatos;

/**
 *
 * @author Meki
 */
public class Formulario extends javax.swing.JFrame {

    ManejadorDatos manejador;
    String info;
    String mensajeServer;
    Client cliente;

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        this.manejador = new ManejadorDatos();
        getContentPane().setBackground(new java.awt.Color(209, 228, 236));
        initComponents();
        this.info = "";
        this.mensajeServer = "";
        this.grupo.setVisible(false);
        this.vacunatorio.setVisible(false);
        this.localidad.setVisible(false);
        this.grupolbl.setVisible(false);
        this.localidadlbl.setVisible(false);
        this.vacunatoriolbl.setVisible(false);
        this.noHabilitado.setVisible(false);

        cliente = new Client();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        si = new javax.swing.JCheckBox();
        no = new javax.swing.JCheckBox();
        disponibilidad = new javax.swing.JButton();
        agendar = new javax.swing.JButton();
        grupo = new javax.swing.JLabel();
        vacunatorio = new javax.swing.JLabel();
        localidad = new javax.swing.JLabel();
        grupolbl = new javax.swing.JLabel();
        vacunatoriolbl = new javax.swing.JLabel();
        localidadlbl = new javax.swing.JLabel();
        noHabilitado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client_ucu/files/coronavirus.png"))); // NOI18N
        jLabel1.setFocusable(false);

        cedula.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cedula.setBorder(null);
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Cedula de Identidad");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Posibilidad de desplazarse a vacunatorios lejanos.");

        si.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        si.setActionCommand("SI");
        si.setLabel("SI");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        no.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        no.setText("NO");
        no.setActionCommand("SI");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        disponibilidad.setBackground(new java.awt.Color(255, 255, 255));
        disponibilidad.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        disponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client_ucu/files/buscar.jpg"))); // NOI18N
        disponibilidad.setText("Buscar Disponibilidad");
        disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibilidadActionPerformed(evt);
            }
        });

        agendar.setBackground(new java.awt.Color(255, 255, 255));
        agendar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        agendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client_ucu/files/agendar.png"))); // NOI18N
        agendar.setText("Agendar");
        agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarActionPerformed(evt);
            }
        });

        grupo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        grupo.setForeground(new java.awt.Color(0, 153, 0));
        grupo.setText("grupo");

        vacunatorio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        vacunatorio.setForeground(new java.awt.Color(0, 153, 0));
        vacunatorio.setText("vacunatorio");

        localidad.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        localidad.setForeground(new java.awt.Color(0, 153, 0));
        localidad.setText("Localidad");
        localidad.setToolTipText("");

        grupolbl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        grupolbl.setText("Asignado a grupo: ");

        vacunatoriolbl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        vacunatoriolbl.setText("Vacunatorio:");

        localidadlbl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        localidadlbl.setText("Localidad:");

        noHabilitado.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        noHabilitado.setForeground(new java.awt.Color(255, 0, 0));
        noHabilitado.setText("No habilitado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grupolbl)
                                .addGap(18, 18, 18)
                                .addComponent(grupo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vacunatoriolbl)
                                            .addComponent(localidadlbl))
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vacunatorio)
                                            .addComponent(localidad)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(agendar)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(61, 61, 61)
                                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(disponibilidad)
                                .addGap(73, 73, 73)
                                .addComponent(noHabilitado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no)
                                    .addComponent(si))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(si))
                .addGap(7, 7, 7)
                .addComponent(no)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disponibilidad)
                    .addComponent(noHabilitado))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupolbl)
                    .addComponent(grupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vacunatorio)
                    .addComponent(vacunatoriolbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad)
                    .addComponent(localidadlbl))
                .addGap(43, 43, 43)
                .addComponent(agendar)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        if (this.si.isSelected()) {
            this.no.setSelected(false);
        }
    }//GEN-LAST:event_siActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        if (this.no.isSelected()) {
            this.si.setSelected(false);
        } // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibilidadActionPerformed

        if (!this.cedula.getText().isEmpty()) {

            this.manejador.manejarDatos(this.cedula.getText());
            this.info = this.manejador.manejarDatos(this.cedula.getText());
            setearLabels();
        } else {
            this.grupolbl.setVisible(false);
            this.vacunatoriolbl.setVisible(false);
            this.localidadlbl.setVisible(false);
            this.grupo.setVisible(false);
            this.vacunatorio.setVisible(false);
            this.localidad.setVisible(false);
            this.noHabilitado.setVisible(false);
            JOptionPane.showMessageDialog(null, "Debe ingresar su CI");
        }
        if (this.cedula.getText().isEmpty()) {
            this.info = "";
            reSetearLabels();
        }


    }//GEN-LAST:event_disponibilidadActionPerformed

    private void agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarActionPerformed

        if (this.info.equals("")) {
            JOptionPane.showMessageDialog(null, "Error al intentar agendarse", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            String[] linea = this.info.split("\\|");
           
                this.mensajeServer = linea[0] + "|" + linea[1] + "|" + linea[2] + "|true|" + linea[4];

           
        }
        try{
            this.cliente.startConnection("192.168.56.1", 80);
            String response = this.cliente.sendMessage(this.mensajeServer);
            JOptionPane.showMessageDialog(null, "Respuesta del Servidor: " + response, "Información", JOptionPane.INFORMATION_MESSAGE);
            this.cliente.stopConnection();
        }catch ( Exception e ) {
//            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error al conectarse al servidor", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_agendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    public void setearLabels() {

        if (this.info.equals("")) {
            this.grupolbl.setVisible(false);
            this.vacunatoriolbl.setVisible(false);
            this.localidadlbl.setVisible(false);
            this.grupo.setVisible(false);
            this.vacunatorio.setVisible(false);
            this.localidad.setVisible(false);
            this.noHabilitado.setVisible(true);

        } else {
            String[] linea = this.info.split("\\|");
            this.noHabilitado.setVisible(false);
            this.grupolbl.setVisible(true);
            this.vacunatoriolbl.setVisible(true);
            this.localidadlbl.setVisible(true);
            this.grupo.setForeground(Color.GREEN.darker());
            this.vacunatorio.setForeground(Color.GREEN.darker());
            this.grupo.setVisible(true);
            this.vacunatorio.setVisible(true);
            this.localidad.setVisible(true);
            this.grupo.setText(linea[4]);
            this.vacunatorio.setText(linea[2]);
            this.localidad.setText(linea[1]);
        }
    }

    public void reSetearLabels() {

        this.grupo.setText("");
        this.vacunatorio.setText("");
        this.localidad.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendar;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton disponibilidad;
    private javax.swing.JLabel grupo;
    private javax.swing.JLabel grupolbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel localidad;
    private javax.swing.JLabel localidadlbl;
    private javax.swing.JCheckBox no;
    private javax.swing.JLabel noHabilitado;
    private javax.swing.JCheckBox si;
    private javax.swing.JLabel vacunatorio;
    private javax.swing.JLabel vacunatoriolbl;
    // End of variables declaration//GEN-END:variables
}
